version: '3.9'
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "7862:7860"
      - "5001:5001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_AUTH_TOKEN=${HUGGINGFACE_AUTH_TOKEN}
    volumes:
      - .:/app
      - python-packages:/root/.local/share
      - hf-cache:/root/.cache
    command:
      python3 server.py
    # entrypoint: >
    #   jupyter-lab
    #   --allow-root
    #   --ip=0.0.0.0
    #   --port=9999
    #   --no-browser
    #   --NotebookApp.token=''
    #   --notebook-dir=/app

    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

volumes:
  python-packages:
    name: python-packages
  hf-cache:
    name: hf-cache
